ParkHorizontalSize = 70 # Ширина парковки
ParkVerticalSize = 100 # Длина парковки
CarHorizontalSize = 1.5 # Ширина авто
CarVerticalSize = 3.8 # Длина авто
VerticalRoadSize = 3 # Ширина вертикального проезда
HorizontalRoadSize = 5 # Ширина горизонтального проезда
MaxDeviation = 0.05 # Насколько максимум может быть поставлена машина от реальных координат
Dencity = 0.75 # Плотность
Car_range = 0.2 # расстояние между машинами
VerticalRoadCount = 2 # Кол-во вертикальных проездов
Type = "Consistent" # Тип парковки
AutoType = "Auto" # Тип авто
ParkingsCount = 5 # Количество парковок